version: 2.1

commands:
  # Save and restore NPM stuff between builds for perf
  save_npm_cache:
    steps:
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
  restore_npm_cache:
    steps:
      - restore_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package.json" }}

  # Save and restore the entire project directory for use between jobs
  save_project:
    steps:
      - save_cache:
          key: v1-checkout-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
            - ~/.cache # For Cypress binary + among other things
  restore_project:
    steps:
      - restore_cache:
          key: v1-checkout-{{ .Environment.CIRCLE_SHA1 }}

  # Save and restore the build between jobs for deployment purposes
  save_build:
    steps:
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./public
  restore_build:
    steps:
      - restore_cache:
          keys:
            - v1-checkout-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-build-{{ .Environment.CIRCLE_SHA1 }}

  # Switch Firebase environments
  use_firebase_dev:
    steps:
      - run:
          name: Use Firebase dev environemnt
          command: npm run firebase:use-dev -- --token=$FIREBASE_TOKEN_DEV

executors:
  default:
    docker:
      - image: cypress/browsers:chrome69
    working_directory: ~/project

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install -g npm@latest'
      - restore_npm_cache
      - run:
          name: install-npm
          command: npm ci
      - save_npm_cache
      - save_project

  # Requires setup
  build:
    executor: default
    steps:
      - restore_project
      - run:
          name: Parcel prod build
          command: npm run parcel:build
      - save_build

  # Requires setup
  lint:
    executor: default
    steps:
      - restore_project
      - run:
          name: ESLint check
          command: npm run eslint

  # Requires setup
  unit_test:
    executor: default
    steps:
      - restore_project
      - run:
          name: Jest
          command: npm run jest

  # Requires setup
  typecheck:
    executor: default
    steps:
      - restore_project
      - run:
          name: TypeScript check
          command: npm run tsc:check

  # Requires build
  cypress:
    executor: default
    steps:
      - restore_build
      - use_firebase_dev
      - run:
          name: Cypress
          command: ./node_modules/.bin/start-server-and-test "npm run firebase:serve -- --token=$FIREBASE_TOKEN_DEV" http://localhost:5000 "npm run cypress:run -- --record --key $CYPRESS_KEY"

  # Requires build
  deploy_dev:
    executor: default
    steps:
      - restore_build
      - use_firebase_dev
      - run:
          name: Deploy to Firebase dev environemnt
          command: npm run firebase:deploy -- --token=$FIREBASE_TOKEN_DEV

workflows:
  version: '2'
  
  build_and_deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - typecheck:
          requires:
            - setup
      - unit_test:
          requires:
            - setup
      - build:
          requires:
            - setup
            - lint
            - typecheck
            - unit_test
      - cypress:
          requires:
            - build
      - deploy_dev:
          requires:
            - build
            - cypress
          filters:
            branches:
              only: master
